import type { WorldCupLanguage } from "./types";

export const WORLD_CUP_LANGUAGE_STORAGE_KEY = "nira-worldcup2026-language";

export const worldcupCopy = {
  zh: {
    languageName: "中文",
    nav: {
      powered: "Powered by nira.social",
      record: "战绩",
      schedule: "赛程",
      bankroll: "模拟实盘",
      cards: "传播卡片",
    },
    hero: {
      eyebrow: "2026 世界杯 · 公开演化实验",
      title: "用 104 场世界杯，公开演化一个有限世界模型",
      titleAlt: "104 Matches to Evolve a Bounded World Model",
      intro:
        "Nira.social 用一个有限、连续、可验证的比赛世界，展示模型如何在赛前推演胜平负方向，并在结果出现后更新自身。",
      primaryCta: "查看赛程演化表",
      secondaryCta: "保存传播卡片",
      boundary: "AI 世界模型公开实验。仅展示模型推演和纸面结果，不提供真实资金操作入口。",
    },
    record: {
      title: "当前模型战绩",
      accuracy: "正确率",
      predicted: "已预测场次",
      correct: "命中场次",
      total: "总场次",
      currentStreak: "当前连续预测正确",
      bestStreak: "最高连续正确",
      matches: "场",
      updated: "最近更新",
    },
    next: {
      title: "下一场推演",
      matchup: "墨西哥 vs 南非",
      directionLabel: "模型预测方向",
      direction: "墨西哥胜",
      confidence: "中等置信",
      simulation: "1,000 场模拟已完成",
      kickoff: "开赛时间",
      published: "推演发布时间",
    },
    schedule: {
      kicker: "赛程演化",
      title: "赛程演化表",
      description: "主线只保留小组赛和淘汰赛；小组赛按当前选中日期展示，不一次摊开全部 72 场。",
      groupStage: "小组赛",
      knockoutStage: "淘汰赛",
      selectedDate: "当前日期",
      dateRailNote: "日期和比赛时间均按北京时间（Asia/Shanghai / BJT）渲染，底层 mock 数据保留 UTC 时间戳。",
      match: "第",
      group: "组",
      prediction: "模型预测",
      result: "结果",
      correct: "命中 ✓",
      missed: "未命中",
      scheduled: "待推演",
      simulating: "正在推演",
      noMatches: "当前日期暂无小组赛。",
      knockoutNote: "淘汰赛先展示晋级路径占位，后续可由真实赛程替换。",
    },
    bankroll: {
      kicker: "模拟实盘",
      title: "模拟实盘展示",
      liveProfit: "实时纸面收益",
      cumulativeStake: "累计模拟投入",
      currentReturn: "当前模拟回收",
      roi: "纸面收益率",
      ledger: "最近模拟账本",
      stake: "模拟投入",
      paperProfit: "纸面收益",
      settledAt: "结算时间",
    },
    simulations: {
      title: "模拟世界里的 1000 场比赛",
      completed: "已完成模拟",
      running: "正在模拟",
      completedLine: "完成 1,000 / 1,000 场",
      runningLine: "阶段性模拟结果",
      updated: "最近更新",
      progress: "已完成",
      resultShare: "三方结果比例",
      draw: "平局",
    },
    agents: {
      title: "30 个 AI 代理，先争论，再预测",
      description: "5 个主 Agent 负责战术、节奏、风险、数据和控制；25 个副 Agent 对每个方向做校验、反驳和置信度修正。",
      subAgentLabel: "5 个副 Agent 正在校验",
      load: "当前负载",
    },
    log: {
      kicker: "演化日志",
      title: "模型更新日志",
      status: "持续运行",
    },
    evolves: {
      kicker: "模型演化",
      title: "模型如何演化",
      description: "不同代理在同一个有限世界里循环推演、反驳和校正，直到形成当前可公开验证的方向。",
      core: "有限世界模型",
      nodes: ["战术", "节奏", "风险", "数据", "控制"],
      labels: ["反事实检查", "可信度校正", "风险扰动", "路径分歧"],
    },
    social: {
      kicker: "传播卡片",
      title: "可保存的传播卡片",
      description: "本轮先预留导出按钮和成品卡片样式；卡片突出谁胜，胜率、模拟次数和连续命中作为辅助信息。",
      winDirection: "谁胜",
      direction: "墨西哥胜",
      accuracy: "胜率",
      simulations: "1000 场模拟",
      streak: "连续命中",
      footer: "nira.social/worldcup2026",
      pending: "功能占位",
    },
    footer: {
      line: "Nira.social · 2026 世界杯有限世界模型公开实验",
      note: "所有数据为 typed mock data，真实赛程和真实模型结果后续可替换接入。",
    },
    directions: {
      home: "主队胜",
      draw: "平",
      away: "客队胜",
      win: "胜",
    },
  },
  en: {
    languageName: "English",
    nav: {
      powered: "Powered by nira.social",
      record: "Record",
      schedule: "Schedule",
      bankroll: "Bankroll",
      cards: "Cards",
    },
    hero: {
      eyebrow: "World Cup 2026 · Public Evolution Experiment",
      title: "104 Matches to Evolve a Bounded World Model",
      titleAlt: "用 104 场世界杯，公开演化一个有限世界模型",
      intro:
        "Nira.social uses a bounded, continuous, verifiable match world to show how the model reasons over win-draw-loss directions before kickoff and updates after results arrive.",
      primaryCta: "View Schedule Board",
      secondaryCta: "Save Sharing Cards",
      boundary: "A public AI world-model experiment. It shows model reasoning and paper results only.",
    },
    record: {
      title: "Live Model Record",
      accuracy: "Accuracy",
      predicted: "Predicted matches",
      correct: "Correct matches",
      total: "Total matches",
      currentStreak: "Current correct streak",
      bestStreak: "Best correct streak",
      matches: "matches",
      updated: "Last updated",
    },
    next: {
      title: "Next Simulation",
      matchup: "Mexico vs South Africa",
      directionLabel: "Model direction",
      direction: "Mexico Win",
      confidence: "Medium confidence",
      simulation: "1,000 simulated matches completed",
      kickoff: "Kickoff",
      published: "Published",
    },
    schedule: {
      kicker: "Schedule Evolution",
      title: "Schedule Evolution Board",
      description:
        "The board keeps only two modes: group stage and knockout stage. Group fixtures render by selected date instead of exposing all 72 at once.",
      groupStage: "Group stage",
      knockoutStage: "Knockout",
      selectedDate: "Selected date",
      dateRailNote: "Dates and match times render in America/New_York / ET from UTC mock timestamps.",
      match: "Match",
      group: "Group",
      prediction: "Model prediction",
      result: "Result",
      correct: "Correct ✓",
      missed: "Missed",
      scheduled: "Scheduled",
      simulating: "Simulating",
      noMatches: "No group-stage matches for this date.",
      knockoutNote: "Knockout paths use placeholders until real fixtures replace the mock data.",
    },
    bankroll: {
      kicker: "Paper Bankroll",
      title: "Paper Bankroll",
      liveProfit: "Live paper profit",
      cumulativeStake: "Paper stake",
      currentReturn: "Paper return",
      roi: "Paper ROI",
      ledger: "Recent paper ledger",
      stake: "Paper stake",
      paperProfit: "Paper profit",
      settledAt: "Settled",
    },
    simulations: {
      title: "1,000 Matches in the Simulated World",
      completed: "Completed",
      running: "Running",
      completedLine: "Completed 1,000 / 1,000 matches",
      runningLine: "Interim simulation result",
      updated: "Last updated",
      progress: "Completed",
      resultShare: "Three-way result share",
      draw: "Draw",
    },
    agents: {
      title: "30 AI Agents Debate Before They Predict",
      description:
        "Five lead agents analyze tactics, momentum, risk, data, and control signals while 25 sub-agents challenge, validate, and calibrate confidence.",
      subAgentLabel: "5 sub-agents validating",
      load: "Current load",
    },
    log: {
      kicker: "Evolution Log",
      title: "Model Evolution Log",
      status: "Live system",
    },
    evolves: {
      kicker: "Model Evolution",
      title: "How the Model Evolves",
      description:
        "Agents repeatedly simulate, challenge, and calibrate inside the same bounded world until a public direction is ready to verify.",
      core: "Bounded World Model",
      nodes: ["Tactics", "Momentum", "Risk", "Data", "Control"],
      labels: ["Counterfactual check", "Confidence calibration", "Risk perturbation", "Path divergence"],
    },
    social: {
      kicker: "Sharing Cards",
      title: "Saveable Sharing Cards",
      description:
        "Export actions are placeholders in this round, but the UI reserves finished card formats where win direction is the dominant signal.",
      winDirection: "Win direction",
      direction: "Mexico Win",
      accuracy: "Win share",
      simulations: "1,000 simulations",
      streak: "Correct streak",
      footer: "nira.social/worldcup2026",
      pending: "Placeholder",
    },
    footer: {
      line: "Nira.social · World Cup 2026 bounded world model public experiment",
      note: "All data is typed mock data; real fixtures and real model results can replace it later.",
    },
    directions: {
      home: "Home win",
      draw: "Draw",
      away: "Away win",
      win: "Win",
    },
  },
} as const satisfies Record<WorldCupLanguage, Record<string, unknown>>;
